name: Secure Action
description: Secure Action is GitHub Actions to run any pre-defined tasks securely
author: Shunsuke Suzuki
branding:
  icon: shield
  color: blue
inputs:
  action:
    description: The action to run
    required: false
  handler:
    description: The handler to use
    required: false
  data:
    description: The data to send
    required: false
  tasks:
    description: Tasks
    required: false
  github_token:
    description: The GitHub token to use
    required: false
    default: ${{github.token}}
  server_repository:
    description: Server repository name
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/index.js"
