name: Bug Report
description: If something isn't working as expected.
labels:
  - bug
body:
  - type: textarea
    id: version
    attributes:
      label: version
      description: Please use the latest version.
    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: Overview
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: |
        GitHub Actions Workflows should be not partial but complete configuration.
        Please remove unneeded configuration to reproduce the issue.
      value: |
        GitHub Actions Workflow

        ```yaml

        ```
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: Note
    validations:
      required: false
